name: 手动更新

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '要更新的分支（默认 main）'
        required: false
        default: 'main'
      upstream:
        description: '上游仓库的 URL（默认 https://github.com/samqin123/MoonTV.git）'
        required: false
        default: 'https://github.com/samqin123/MoonTV.git'

jobs:
  manual-update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: 循环：设置上游远程
        run: |
          # 如果已经存在 upstream 则先移除再添加，避免重复报错
          git remote remove upstream 2>/dev/null || true
          git remote add upstream "${{ inputs.upstream }}"

      - name: 循环：拉取上游更新
        run: |
          git fetch upstream --prune

      - name: 循环：合并上游到当前分支
        run: |
          git checkout "${{ inputs.branch }}"
          # 先尝试快进合并，若不行则创建合并提交
          if git merge --ff-only "upstream/${{ inputs.branch }}"; then
            echo "快进合并成功"
          else
            git merge "upstream/${{ inputs.branch }}" --allow-unrelated-histories -m "循环：手动同步上游更新"
          fi

      - name: 推送更改到复刻仓库
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin "${{ inputs.branch }}"
